name: Frontend CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate HTML Files
        run: |
          echo "Checking HTML files..."
          find . -name "*.html"

      - name: Validate CSS Files
        run: |
          echo "Checking CSS files..."
          find . -name "*.css"

      - name: Validate JavaScript Files
        run: |
          echo "Checking JS files..."
          find . -name "*.js"

      - name: CI Passed
        run: echo "Frontend validation completed successfully."